'use strict';
const Parser = require('rss-parser');
const {createHash} = require('node:crypto');
const parser = new Parser({timeout:12000,headers:{'User-Agent':'KoreanIssueMonitor/1.0'}});
const WINDOWS = { '1h':3600000, '24h':86400000, '7d':604800000 };
const CATEGORIES = [ ['정치',/대통령|국회|정부|선거|정당|의원|장관|탄핵|정책/], ['사건·사고',/사고|화재|사망|부상|실종|폭발|지진|침수|재난|범죄/], ['행사',/축제|공연|콘서트|전시|행사|개막|대회/], ['경제',/주가|금리|환율|물가|기업|증시|부동산/], ['생활',/날씨|교통|학교|병원|건강|교육|주택/] ];
const STOP = new Set('오늘 최근 관련 대한 한국 서울 뉴스 속보 단독 영상 공개 진행 발표 있다 했다 것으로 대해 그리고 이번 기자 사진 해당 통해 이후 오전 오후 에서 으로 하는 한다'.split(' '));
function clean(value){return String(value||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim().slice(0,600);}
function keywords(text){const words=(clean(text).match(/[가-힣]{2,}|[A-Za-z][A-Za-z0-9]{2,}|#[가-힣A-Za-z0-9_]+/g)||[]).map(w=>w.toLowerCase().replace(/(으로|에서|에게|부터|까지|로|은|는|이|가|을|를)$/,m=>w.length>m.length+1?'':m));const count=new Map();for(const w of words)if(!STOP.has(w))count.set(w,(count.get(w)||0)+1);return [...count].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'ko')).slice(0,8).map(x=>x[0]);}
function classify(text){return CATEGORIES.find(([,re])=>re.test(text))?.[0]||'기타';}
function normalized(raw){const url=raw.url||raw.link||'';const title=clean(raw.title);if(!title||!/^https?:\/\//.test(url))return null;const publishedAt=new Date(raw.publishedAt||raw.isoDate||raw.pubDate||Date.now());if(Number.isNaN(+publishedAt))return null;const summary=clean(raw.summary||raw.contentSnippet||raw.description||title).slice(0,300);const key=url.replace(/[?#].*$/,'').replace(/\/$/,'');return {id:createHash('sha256').update(key).digest('hex'),title,summary,url,source:raw.source||'뉴스',channel:raw.channel||raw.source||'뉴스',publishedAt:publishedAt.toISOString(),keywords:keywords(title+' '+summary),category:classify(title+' '+summary)};}
async function newsSearch(query,window){const end=new Date(),start=new Date(end-WINDOWS[window]);const url='https://news.google.com/rss/search?q='+encodeURIComponent(query+' after:'+start.toISOString().slice(0,10))+'&hl=ko&gl=KR&ceid=KR:ko';const feed=await parser.parseURL(url);return (feed.items||[]).slice(0,100).map(item=>normalized({...item,source:'Google 뉴스',url:item.link})).filter(x=>x&&Date.parse(x.publishedAt)>=+start);}
async function youtubeSearch(query,window,key){if(!key)return {items:[],quota:0,status:'unconfigured'};const url=new URL('https://www.googleapis.com/youtube/v3/search');url.search=new URLSearchParams({part:'snippet',q:query,type:'video',order:'date',maxResults:'25',regionCode:'KR',relevanceLanguage:'ko',publishedAfter:new Date(Date.now()-WINDOWS[window]).toISOString(),key}).toString();const res=await fetch(url,{signal:AbortSignal.timeout(12000)});if(!res.ok)throw new Error('YouTube HTTP '+res.status);const data=await res.json();return {items:(data.items||[]).map(x=>normalized({title:x.snippet?.title,summary:x.snippet?.description,url:'https://www.youtube.com/watch?v='+x.id?.videoId,source:'YouTube',channel:x.snippet?.channelTitle,publishedAt:x.snippet?.publishedAt})).filter(Boolean),quota:100,status:'ok'};}
function clusters(items,window,now=Date.now()){const span=WINDOWS[window],current=items.filter(i=>now-Date.parse(i.publishedAt)<=span),prior=items.filter(i=>{const age=now-Date.parse(i.publishedAt);return age>span&&age<=2*span});const counts=new Map();for(const item of current)for(const word of item.keywords.slice(0,5)){let c=counts.get(word);if(!c)counts.set(word,c={keyword:word,items:[],sources:new Set()});c.items.push(item);c.sources.add(item.source);}return [...counts.values()].filter(c=>c.items.length>=2).map(c=>{const before=prior.filter(i=>i.keywords.includes(c.keyword)).length;const growth=before?Math.round((c.items.length-before)/before*100):null;const score=Math.round(c.items.length*2+Math.max(0,growth||0)/50+c.sources.size*3);const newest=c.items.sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt))[0];return {keyword:c.keyword,count:c.items.length,previousCount:before,growthPercent:growth,sourceCount:c.sources.size,score,category:newest.category,summary:newest.title,updatedAt:newest.publishedAt,itemIds:c.items.map(i=>i.id)};}).sort((a,b)=>b.score-a.score).slice(0,100);}
function init(db){db.exec(`CREATE TABLE IF NOT EXISTS korean_jobs(id INTEGER PRIMARY KEY,query TEXT NOT NULL,window TEXT NOT NULL,sources TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,finished_at TEXT,results INTEGER NOT NULL DEFAULT 0,error TEXT);CREATE TABLE IF NOT EXISTS korean_items(id TEXT PRIMARY KEY,data TEXT NOT NULL,first_seen TEXT NOT NULL,last_seen TEXT NOT NULL);CREATE TABLE IF NOT EXISTS korean_job_items(job_id INTEGER NOT NULL,item_id TEXT NOT NULL,PRIMARY KEY(job_id,item_id));CREATE TABLE IF NOT EXISTS korean_logs(id INTEGER PRIMARY KEY,created_at TEXT NOT NULL,level TEXT NOT NULL,source TEXT NOT NULL,message TEXT NOT NULL);CREATE TABLE IF NOT EXISTS korean_usage(day TEXT PRIMARY KEY,youtube_units INTEGER NOT NULL DEFAULT 0);CREATE INDEX IF NOT EXISTS korean_items_seen ON korean_items(last_seen);`);}
function createService(db,{searchNews=newsSearch,searchYouTube=youtubeSearch,now=()=>new Date(),youtubeKey=process.env.YOUTUBE_API_KEY||'',dailyBudget=Number(process.env.YOUTUBE_DAILY_BUDGET||1000)}={}){init(db);let active=null;const log=(level,source,message)=>db.prepare('INSERT INTO korean_logs(created_at,level,source,message) VALUES(?,?,?,?)').run(now().toISOString(),level,source,String(message).slice(0,500));
async function run({query,window='24h',sources=['news','youtube']}={}){query=clean(query);if(query.length<2||query.length>100||!WINDOWS[window]||!Array.isArray(sources)||!sources.length||sources.some(s=>!['news','youtube'].includes(s)))throw Object.assign(new Error('검색어, 기간 또는 소스를 확인하세요'),{status:400});if(active)throw Object.assign(new Error('수집 작업이 실행 중입니다'),{status:409});const promise=(async()=>{const job=Number(db.prepare('INSERT INTO korean_jobs(query,window,sources,status,created_at) VALUES(?,?,?,?,?)').run(query,window,JSON.stringify(sources),'running',now().toISOString()).lastInsertRowid);let total=0,errors=[];for(const source of sources){try{let result;if(source==='news')result={items:await searchNews(query,window),quota:0,status:'ok'};else{const day=now().toISOString().slice(0,10),used=db.prepare('SELECT youtube_units n FROM korean_usage WHERE day=?').get(day)?.n||0;if(!youtubeKey){log('warn','youtube','YOUTUBE_API_KEY가 설정되지 않았습니다');continue;}if(used+100>dailyBudget){log('warn','youtube','일일 YouTube 예산 초과');continue;}db.prepare('INSERT INTO korean_usage(day,youtube_units) VALUES(?,100) ON CONFLICT(day) DO UPDATE SET youtube_units=youtube_units+100').run(day);result=await searchYouTube(query,window,youtubeKey);}for(const raw of result.items){const item=raw.id?raw:normalized(raw);if(!item)continue;db.prepare('INSERT INTO korean_items(id,data,first_seen,last_seen) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,last_seen=excluded.last_seen').run(item.id,JSON.stringify(item),now().toISOString(),now().toISOString());db.prepare('INSERT OR IGNORE INTO korean_job_items(job_id,item_id) VALUES(?,?)').run(job,item.id);total++;}log('info',source,`${total}건 수집`);}catch(e){errors.push(`${source}: ${e.message}`);log('error',source,e.message);}}const status=errors.length?(total?'partial':'failed'):'done';db.prepare('UPDATE korean_jobs SET status=?,finished_at=?,results=?,error=? WHERE id=?').run(status,now().toISOString(),total,errors.join('; ')||null,job);return {id:job,status,results:total,errors};})();active=promise;try{return await promise;}finally{active=null;}}
function items({limit=100,query='',source='',window='7d'}={}){const cutoff=new Date(+now()-WINDOWS[window]).toISOString();return db.prepare('SELECT data FROM korean_items WHERE json_extract(data,\'$.publishedAt\')>=? ORDER BY json_extract(data,\'$.publishedAt\') DESC LIMIT 2000').all(cutoff).map(r=>JSON.parse(r.data)).filter(i=>(!query||(i.title+' '+i.summary).toLowerCase().includes(query.toLowerCase()))&&(!source||i.source.toLowerCase().includes(source.toLowerCase()))).slice(0,limit);}
function issues(window='24h'){const cutoff=new Date(+now()-2*WINDOWS[window]).toISOString();const rows=db.prepare("SELECT data FROM korean_items WHERE json_extract(data,'$.publishedAt')>=? ORDER BY json_extract(data,'$.publishedAt') DESC LIMIT 3000").all(cutoff).map(r=>JSON.parse(r.data));return clusters(rows,window,+now());}
function operations(){const day=now().toISOString().slice(0,10);return {jobs:db.prepare('SELECT * FROM korean_jobs ORDER BY id DESC LIMIT 20').all().map(j=>({...j,sources:JSON.parse(j.sources)})),logs:db.prepare('SELECT * FROM korean_logs ORDER BY id DESC LIMIT 30').all(),usage:{youtubeUnits:db.prepare('SELECT youtube_units n FROM korean_usage WHERE day=?').get(day)?.n||0,dailyBudget},counts:{items:db.prepare('SELECT count(*) n FROM korean_items').get().n,jobs:db.prepare('SELECT count(*) n FROM korean_jobs').get().n},active:!!active};}
return {run,items,issues,operations,log};}
module.exports={WINDOWS,normalized,keywords,classify,clusters,createService};
