'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const Database=require('better-sqlite3');const {normalized,keywords,clusters,createService}=require('../korean');
test('Korean normalization and issue detection',()=>{const a=normalized({title:'서울 폭우로 도로 침수',url:'https://example.com/a?ref=1',source:'뉴스',publishedAt:'2026-09-28T00:00:00Z'});const b=normalized({title:'서울 폭우 피해 확산',url:'https://example.com/b',source:'YouTube',publishedAt:'2026-09-28T00:10:00Z'});assert.equal(a.category,'사건·사고');assert.equal(a.id,normalized({title:a.title,url:'https://example.com/a?ref=2'}).id);assert.ok(keywords(a.title).includes('폭우로')||keywords(a.title).includes('폭우'));assert.ok(clusters([a,b],'24h',Date.parse('2026-09-28T01:00:00Z')).length>0)});
test('search stores jobs, items and source failures',async()=>{const db=new Database(':memory:');const service=createService(db,{now:()=>new Date('2026-09-28T01:00:00Z'),searchNews:async()=>[{title:'서울 지하철 사고 발생',url:'https://example.com/1',source:'뉴스',publishedAt:'2026-09-28T00:00:00Z'}],searchYouTube:async()=>{throw Error('quota')},youtubeKey:'test'});const r=await service.run({query:'서울 사고',sources:['news','youtube']});assert.equal(r.status,'partial');assert.equal(service.items().length,1);assert.equal(db.prepare('SELECT count(*) n FROM korean_source_items').get().n,1);assert.equal(service.operations().usage.youtubeSearchCalls,1);await assert.rejects(service.run({query:'x'}),/검색어/);db.close()});
test('domestic activities carry coverage and a location only when a place is named',async()=>{const db=new Database(':memory:');const service=createService(db,{now:()=>new Date('2026-09-28T01:00:00Z'),searchNews:async()=>[{title:'서울 폭우 도로 침수',url:'https://example.com/a',publishedAt:'2026-09-28T00:00:00Z'},{title:'서울 폭우 피해 확대',url:'https://example.com/b',publishedAt:'2026-09-28T00:10:00Z'}]});await service.run({query:'서울 폭우',sources:['news']});const activity=service.activities().find(x=>x.keyword==='폭우');assert.equal(activity.location.name,'서울');assert.equal(activity.articles.length,2);db.close()});

test('trends signal, cache, issue snapshots and review decisions persist',async()=>{const db=new Database(':memory:');let calls=0;const service=createService(db,{now:()=>new Date('2026-09-28T01:00:00Z'),searchTrends:async()=>{calls++;return [{title:'폭우 피해 확대',url:'https://trends.google.com/trends/explore?q=폭우',source:'Google 트렌드',publishedAt:'2026-09-28T00:10:00Z'},{title:'폭우 발생 지역',url:'https://trends.google.com/trends/explore?q=폭우2',source:'Google 트렌드',publishedAt:'2026-09-28T00:15:00Z'}]}});const first=await service.run({query:'',sources:['trends']});const second=await service.run({query:'',sources:['trends']});assert.equal(first.id,second.id);assert.equal(second.cached,true);assert.equal(calls,1);assert.ok(service.history('폭우').length>0);service.review('폭우','dismissed','오탐');assert.equal(service.issues().find(i=>i.keyword==='폭우').review.decision,'dismissed');assert.equal(service.activities().find(i=>i.keyword==='폭우').review.decision,'dismissed');assert.equal(service.operations().sources[0].status,'ok');db.close();});
test('event clusters merge related coverage but not a single shared broad word',()=>{const now=Date.parse('2026-09-28T01:00:00Z');const items=[{title:'부산 항만 화재 부상자 발생',url:'https://a.test/1',source:'뉴스',publishedAt:'2026-09-28T00:00:00Z'},{title:'부산 항만 화재 진압 중',url:'https://b.test/2',source:'YouTube',publishedAt:'2026-09-28T00:10:00Z'},{title:'부산 축제 개막',url:'https://c.test/3',source:'뉴스',publishedAt:'2026-09-28T00:20:00Z'}].map(normalized);const groups=require('../korean').eventClusters(items,'24h',now);assert.equal(groups.length,1);assert.equal(groups[0].count,2);assert.equal(groups[0].sourceCount,2)});
test('optional X search is gated by token and records a source run',async()=>{const db=new Database(':memory:');let called=0;const service=createService(db,{now:()=>new Date('2026-09-28T01:00:00Z'),xToken:'token',searchX:async()=>{called++;return [{title:'부산 항만 화재',url:'https://x.com/i/status/1',source:'X',publishedAt:'2026-09-28T00:00:00Z'}]}});const result=await service.run({query:'부산 화재',sources:['x']});assert.equal(result.status,'done');assert.equal(called,1);assert.equal(service.operations().usage.xSearchCalls,1);assert.equal(service.operations().sources[0].count,1);db.close()});
